public with sharing class Products_ListExtension {
/*
    public Flow.Interview.Products_List myFlow{get;set;}
     public String linItemID{get;set;}
     public ID opptyID{get;set;}


    public Products_ListExtension(ApexPages.StandardController controller) {
        opptyID=ApexPages.currentPage().getParameters().get('id');

    }
    public String getLineItemID()
    {
    if(myFlow==null)
    {
    System.debug('myFlow is null');
    return null;
   
    }
    else{
    linItemID=(String) myFlow.getVariableValue('lineItemID');
        System.debug('Line Item IS: '+linItemID);
    }
    return linItemID;
    }
    public PageReference getfinishPage()
    {
    getLineItemID();
    
    System.debug('finish page');
    String url='https://ap2.salesforce.com/'+opptyID;
   
    PageReference p=new PageReference(url);
    return p;
    }
    */
}